spring:
  application:
    name: bilyoner-case
  datasource:
    url: jdbc:h2:mem:bilyonercase
    driver-class-name: org.h2.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

betslip:
  creation-timeout-second: 2